[theme]
base="light"  # or "light" if you prefer
primaryColor="#FFE600"       # EY Yellow (buttons, highlights)
backgroundColor="#2E2E38"    # Charcoal Black (main background)
secondaryBackgroundColor="#1C1C24"  # Darker shade for cards
textColor="#FFFFFF"          # White text
font="sans serif"            # Clean, modern font
