[theme]
base="light"  # or "light" if you prefer
primaryColor="#1a9afb"       # EY Blue (buttons, highlights)
backgroundColor="#FFFFFF"    # Charcoal Black (main background)
secondaryBackgroundColor="#F5F5F5"  # Darker shade for cards
textColor="#2E2E38"          # White text
font="sans serif"            # Clean, modern font
